# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  j2s7s300_joint_1:
    min_position: -2
    max_position: 1 #3.141592653589793
    has_velocity_limits: true
    max_velocity: 0.78 #0.628318530718
    has_acceleration_limits: false
    max_acceleration: 0
  j2s7s300_joint_2:
    has_velocity_limits: true
    max_velocity: 0.78 #0.628318530718
    has_acceleration_limits: false
    max_acceleration: 0
  j2s7s300_joint_3:
    min_position: 5.5 #4.71238898038469
    max_position: 6.5 #7.853981633974483
    has_velocity_limits: true
    max_velocity: 0.78 #0.628318530718
    has_acceleration_limits: false
    max_acceleration: 0
  j2s7s300_joint_4:
    min_position: 0
    max_position: 3.141592653589793
    has_velocity_limits: true
    max_velocity: 0.78 #0.628318530718
    has_acceleration_limits: false
    max_acceleration: 0
  j2s7s300_joint_5:
    min_position: 1.5707963267948966
    max_position: 4.71238898038469
    has_velocity_limits: true
    max_velocity: 1.0 #0.837758040957
    has_acceleration_limits: false
    max_acceleration: 0
  j2s7s300_joint_6:
    min_position: 0
    max_position: 3.141592653589793
    has_velocity_limits: true
    max_velocity: 1.0 #0.837758040957
    has_acceleration_limits: false
    max_acceleration: 0
  j2s7s300_joint_7:
    has_velocity_limits: true
    max_velocity: 0.785
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_85_left_finger_tip_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_85_left_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_85_left_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_85_right_finger_tip_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_85_right_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_85_right_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
