- name: "Table_segment"
  require_surface: false
  parent_frame_id: "j2s7s300_link_base"
  child_frame_id: "depth_camera_link"
  bounding_frame_id: "j2s7s300_link_base"
  segmentation_frame_id: "j2s7s300_link_base"
  z_min: -0.1
  z_max: 0.2
  y_min: -0.8
  y_max: 0.08
  x_min: -0.75
  x_max: 0.0