Test: {htn_yaml_file: ./htn/human_assm.yaml, pelvis_mean: ./logs/minifocalloss_withrobot/pelvis_mean.npy,
  test_ckpt: ./logs/minifocalloss_withrobot/model_front_bestacc.ckpt}
batch_size: 256
beta: 0.999
learning_rate: 1e-5
logname: minifocalloss_withrobot_extended_full
loss_function: Focal
metadata: /home/comanip/devel_codes/DrillAssm_skeletal/data_withrobot_extended/metadata.yaml
num_epochs: 250
weight_decay: 5e-6
